### ISSUE TITLE
Truncated tweets

### ISSUE THREAD

**Issue by filmenczer** [glciampaglia/infodiversity-mock-social-media#39] opened 2021-04-01 20:50 UTC
Some tweets are truncated. Perhaps these are extended tweets. for which you should get the `full_text ` with `tweet_mode=extended`
<img width="567" alt="Screen Shot 2021-04-01 at 4 32 00 PM" src="https://user-images.githubusercontent.com/10651090/113352487-5336fa00-930a-11eb-9bdd-2dfb77b64d16.png">

**Comment by saumyabhadani95** [comment] 2021-04-04 02:43
We have confirmed in our code that we are using "tweet_mode=extended" and "full_text". Maybe this is an API abnormality?

**Comment by filmenczer** [comment] 2021-04-04 05:37
Maybe because it’s a retweet?

**Comment by glciampaglia** [comment] 2021-04-05 21:00
It seems the issue is caused on retweets only. We using the full text from the tweet itself, which for retweets may be truncated. To solve the issue, we need to check that in the JSON `retweet_status` is True, and if that is the case, look for the full text in the `retweeted_status` sub-object.

**Comment by RobertAndion** [comment] 2021-04-06 00:27
This is now done. Please test as I do not have retweets on my limited feed.

**Comment by filmenczer** [comment] 2021-04-06 00:49
Not quite, sorry. Now a **retweeted tweet looks like it originated form the retweeter**. Here is an example as seen on my feed and on Truman (note the like count is also wrong; not sure about the retweet count):

<img width="593" alt="Screen Shot 2021-04-05 at 8 37 15 PM" src="https://user-images.githubusercontent.com/10651090/113642926-fbbcc500-964e-11eb-88b1-510abdecf039.png">
<img width="562" alt="Screen Shot 2021-04-05 at 8 37 37 PM" src="https://user-images.githubusercontent.com/10651090/113642929-fe1f1f00-964e-11eb-98c4-4d0fd2eafb09.png">

Also, **quoted tweets are not being shown**. Example:

<img width="592" alt="Screen Shot 2021-04-05 at 8 46 09 PM" src="https://user-images.githubusercontent.com/10651090/113643307-0592f800-9650-11eb-99a1-795b1f92c44c.png">
<img width="561" alt="Screen Shot 2021-04-05 at 8 46 26 PM" src="https://user-images.githubusercontent.com/10651090/113643317-07f55200-9650-11eb-84d1-b4cc002478f2.png">

**Comment by glciampaglia** [comment] 2021-04-06 13:13
Thank you @filmenczer. Fixing the retweet case should not be difficult; we simply need to display the screen name / @name of the creator of the original tweet, and put the name of the person who retweeted in an additional line.

For quoted tweets, this may likely require some extra work since now the quoted tweet may have its own card or not, depending on whether it has links or not. Perhaps we should create a separate issue for that. I am marking this for discussion during our next meeting.

**Comment by RobertAndion** [comment] 2021-04-06 23:10
It seems like we can do p! = string to not escape those and see them as emojis (https://github.com/pugjs/pug/issues/2578) This will have to be looked into. The quote will take some extra work and I will take a look at fixing the retweet to show the person with a retweeted by: @username or something similar. I believe Saumya wanted to do this but I will take a quick look.

**Comment by RobertAndion** [comment] 2021-04-06 23:40
I have not solved this in an eloquent way (@saumyabhadani95  can do this in PUG) However I have fixed the backend to do the retweets properly. For now check the body of the tweet for: screen name Retweeted: 
It is not very easy to see and will need GUI improvements as stated. Please let me know if this "looks" correct now. Thank you

**Comment by RobertAndion** [comment] 2021-04-07 15:33
This is now solved except for the username Retweeted: not being as noticeable as it should be. The next issue will be to figure out how to detect when a quote is given. I think I can add it to my logic chain.

**Comment by saumyabhadani95** [comment] 2021-04-08 19:48
I changed the way "Retweeted By" is displayed. It is not displayed on the top of the post with the retweet icon.

Keeping this issue open for handling the quotes.

**Comment by glciampaglia** [comment] 2021-04-19 21:02
We have created a new issue to keep track of quoted tweets (see #46), so we can close this issue.

**Closed by glciampaglia** 2021-04-19 21:02 UTC
Labels: low priority, needs discussion
